### ISSUE TITLE
Installation in a python virtual environment

### ISSUE THREAD

**Issue by leclercfl** [rglez/nuclear#1]
# README #

###  Installation of python packages dependencies ###
(replace $path by your own installation path with default python distribution)

$ python -m venv $path/nuclear
$bash source $path/nuclear/bin/activate # or $csh source $path/nuclear/bin/activate.csh
$ pip install ProDy
$ pip install numpy
$ pip install scikit-learn
$ pip install parmed
$ pip install bitarray
$ pip install pandas
$ pip install line_profiler
$ pip install numba
$ pip install networkx
$ pip install plotly

or, if you have virtualenv installed:
(replace $PATH by your own python path)

$ virtualenv -p $PATH/python3.x $pvenv/nuclear
$ source $pvenv/nuclear/bin/activate
$ pip install ProDy
...

or, if you have virtualenv/virtualenvwrapper installed:

$ mkdirvirtualenv nuclear
$ workon nuclear
$ pip install ProDy
...

## Get NUCLEAR package ##
see instructions at: https://github.com/rglez/nuclear
cd $path
git clone git@github.com:rglez/nuclear.git # or git clone https://github.com/rglez/nuclear.git

### Running nuclear ###

Test example (replace $path by your own nuclear repository path):

$ cd $path/nuclear/tests
$ python $path/nuclear constrained_local_minfalse.cfg

**Comment by leclercfl** [comment]
YES, it would be cleaner ...

**Comment by leclercfl** [comment]
actually I was then installing the nuclear classes into the python environment to have everything in the same place

**Comment by rglez** [comment]
Ok. I will try to publish nuclear in PyPI and after testing, will close this issue.

**Comment by rglez** [comment]
> Ok. I will try to publish nuclear in PyPI and after testing, will close this issue.

Done. Please test it from your side and feel free to close this issue if everything works.
