### ISSUE TITLE
nuclear binary ?

### ISSUE THREAD

**Issue by leclercfl** [rglez/nuclear#6]
$ nuclear path-to-config-file.cfg

what is the expected installed path for nuclear ?

**Comment by rglez** [comment]
After the pip installation, nuclear will be available in your system as an
independent  "entry point". The exact path will depend on the system but it
should be available out of the box.

CI workflow on ubuntu-latest and Python 3.8-3.11 is passing. CI install and
access nuclear as an entry point without explicitly use of the absolute
path.

If you install nuclear into a virtual environment, be sure to activate it
before running. Please test, and feel free to close this issue ;)
